
package com.subbranch.webservices;

import java.util.Map;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://webservices.subbranch.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBpayStatus", targetNamespace = "http://webservices.subbranch.com/", className = "com.subbranch.webservices.GetBpayStatus")
    @ResponseWrapper(localName = "getBpayStatusResponse", targetNamespace = "http://webservices.subbranch.com/", className = "com.subbranch.webservices.GetBpayStatusResponse")
    public String getBpayStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param map
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updBrachReceStatus", targetNamespace = "http://webservices.subbranch.com/", className = "com.subbranch.webservices.UpdBrachReceStatus")
    @ResponseWrapper(localName = "updBrachReceStatusResponse", targetNamespace = "http://webservices.subbranch.com/", className = "com.subbranch.webservices.UpdBrachReceStatusResponse")
    public int updBrachReceStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        Map<String, Object> map);

}
